# Generated by Django 4.0.5 on 2022-06-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicoh', '0002_alter_order_date_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('order', 'product')},
        ),
    ]
